-- Add Map Coordinates to Locations
ALTER TABLE locations 
ADD COLUMN IF NOT EXISTS pos_x INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS pos_y INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS width INTEGER DEFAULT 1,
ADD COLUMN IF NOT EXISTS height INTEGER DEFAULT 1,
ADD COLUMN IF NOT EXISTS rotation INTEGER DEFAULT 0; -- 0, 90, 180, 270

-- Reload Postgrest Config
NOTIFY pgrst, 'reload config';
